services:
  gatus:
    restart: unless-stopped
    image: twinproduction/gatus:v5.36.0
    ports:
      - "8014:8080"
    volumes:
      - ./config:/config
    environment:
      - GATUS_CONFIG_PATH=/config
    env_file: .env