alert-preset: &alert-preset
  send-on-resolved: true

alerting:
  ntfy:
      url: https://ntfy.06222001.xyz
      topic: ${NTFY_TOPIC}
      priority: 5
      <<: *alert-preset
      overrides:
        # Not yet implemented
        # - group: "Service Queue"
          # topic: ${NTFY_TOPIC_SERVICE_QUEUE}
  discord:
      webhook-url: ${DISCORD_WEBHOOK_URL}
      <<: *alert-preset
      # Not yet implemented
      # overrides:
        # - group: "Service Queue"
          # webhook-url: ${DISCORD_WEBHOOK_URL_SERVICE_QUEUE}
  email:
      from: "kuma@ses.aws.06222001.xyz" # Unverified, will only send to personal mailbox
      username: ${SMTP_USERNAME}
      password: ${SMTP_PASSWORD}
      host: "email-smtp.ap-southeast-2.amazonaws.com"
      port: 465
      to: "noehbernasol0@gmail.com"
      <<: *alert-preset
      overrides:
        - group: "Service Queue"
          from: "dummydeedumdum@gmail.com"
          username: ${SMTP_USERNAME_SERVICE_QUEUE}
          password: ${SMTP_PASSWORD_SERVICE_QUEUE}
          host: "smtp.gmail.com"
          port: 587