dns-preset: &dns-preset
  group: DNS - External
  interval: 10s
  conditions:
    - "[CONNECTED] == true"
    - "[RESPONSE_TIME] < 200"
  alerts:
    - type: ntfy
    - type: discord

endpoints:
  - name: Cloudflare - 1.1.1.1
    url: "icmp://1.1.1.1"
    <<: *dns-preset

  - name: Cloudflare - 1.0.0.1
    url: "icmp://1.0.0.1"
    <<: *dns-preset

  - name: Google - 8.8.8.8
    url: "icmp://8.8.8.8"
    <<: *dns-preset

  - name: Google - 8.8.4.4
    url: "icmp://8.8.4.4"
    <<: *dns-preset

  - name: Quad9 - 9.9.9.11
    url: "icmp://9.9.9.11"
    <<: *dns-preset

  - name: Quad9 - 9.9.9.9
    url: "icmp://9.9.9.9"
    <<: *dns-preset