# Presets
service_queue_preset: &service_queue_preset
  group: Service Queue
  interval: 30s
  conditions:
    - "[STATUS] == 200"
  alerts:
    - type: ntfy
    - type: discord
    - type: email

service_queue_preset-silent: &service_queue_preset-silent
  group: Service Queue
  interval: 30s
  conditions:
    - "[STATUS] == 200"
  alerts:
    - type: discord


endpoints:
  - name: Gackkons API
    url: "https://api.gackkons.06222001.xyz"
    <<: *service_queue_preset
    alerts:
      - type: email
        to: "noehbernasol0@gmail.com,jiggerandreigobenza2@gmail.com,margiebalansagfabores@gmail.com"

  - name: Gackkons App
    url: "https://app.gackkons.06222001.xyz"
    <<: *service_queue_preset
    alerts:
      - type: email
        to: "noehbernasol0@gmail.com,jiggerandreigobenza2@gmail.com,margiebalansagfabores@gmail.com"

  - name: Minecraft Server - Okenwald
    url: "tcp://okenwald.06222001.xyz:39702"
    <<: *service_queue_preset
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: email
        to: "noehbernasol0@gmail.com,roitzy.chcdo@gmail.com,edkarmelpiscos9317@gmail.com"

  - name: Minecraft Server - DeceasedCraft
    url: "udp://06222001.xyz:35761"
    <<: *service_queue_preset
    conditions:
      - "[CONNECTED] == true"

  - name: Nominatim API
    url: "https://nominatim.06222001.xyz"
    <<: *service_queue_preset
    alerts:
      - type: email
        to: "noehbernasol0@gmail.com,claudio.daruca@ustp.edu.ph"
    conditions:
      - "[STATUS] == 404"

  - name: OSRM API
    url: "https://osrm.06222001.xyz"
    <<: *service_queue_preset
    alerts:
      - type: email
        to: "noehbernasol0@gmail.com,claudio.daruca@ustp.edu.ph"
    conditions:
      - "[STATUS] == 400"

  - name: TAJMS App
    url: "https://tajms.06222001.xyz"
    <<: *service_queue_preset
    alerts:
      - type: email
        to: "noehbernasol0@gmail.com,galario.rainheart16@gmail.com"

  - name: Minecraft Server - MickeyMouse
    url: "udp://06222001.xyz:22913"
    <<: *service_queue_preset
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: email
        to: "noehbernasol0@gmail.com,renzo2kpro@gmail.com"

  - name: ECE Monitoring System
    url: "https://ecemonitoringsystem.06222001.xyz"
    <<: *service_queue_preset
    alerts:
      - type: email
        to: "noehbernasol0@gmail.com,delapenaprincekurtlaurence@gmail.com,paknotaztig@gmail.com"

  - name: BCBP API (Dev)
    url: "https://api.dev.bcbp.06222001.xyz"
    <<: *service_queue_preset
    alerts:
      - type: email
        to: "noehbernasol0@gmail.com,kenn.nacario12@gmail.com"

  - name: BCBP API (Prod)
    url: "https://app.bcbp-members-portal.xyz"
    <<: *service_queue_preset
    alerts:
      - type: email
        to: "noehbernasol0@gmail.com,kenn.nacario12@gmail.com"