# Deployment step for Woodpecker CI/CD
# Git-backed, images pulled from remote registry

steps:
  - name: deploy
    image: alpine:latest
    environment:
      SSH_KEY:
        from_secret: SSH_KEY
      SSH_HOST: root@five.06222001.xyz
      PROJECT_DIRECTORY: /mnt/sda1/files/docker\ projects/gatus
    commands:
      - apk add openssh
      - mkdir -p /root/.ssh/
      - echo "$SSH_KEY" | tr -d '\r' > /root/.ssh/id_rsa
      - chmod 600 /root/.ssh/id_rsa
      - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > /root/.ssh/config
      - ssh "$SSH_HOST" "
          cd $PROJECT_DIRECTORY;
          docker compose down;
          git restore . && git pull origin $CI_COMMIT_BRANCH --force --rebase;
          rm -fv config/remote.yaml;
          for f in config/*.yaml; do sed -i.bak -E 's/^([[:space:]]*group:[[:space:]]*)(.*)$/\\1Remote - \\2/' \"\$f\" && rm -f \"\$f.bak\"; done;
          docker compose up -d;
          docker image prune -af;
          sleep 60;
          docker compose logs;
        "
    volumes:
      - /var/cache/apk:/etc/apk/cache

when:
  - branch: master
    event:
      - push
      - manual

depends_on:
  - test

skip_clone: true