# Deployment step for Woodpecker CI/CD
# Git-backed, images pulled from remote registry

steps:
  - name: deploy
    image: alpine:latest
    environment:
      BW_CLIENTID:
        from_secret: BW_CLIENT_ID
      BW_CLIENTSECRET:
        from_secret: BW_CLIENT_SECRET
      BW_PASSWORD:
        from_secret: BW_PASSWORD
      SSH_HOST: root@10.0.10.115
      PROJECT_DIRECTORY: /mnt/nvme/files/docker \projects/gatus
      MISE_CACHE_DIR: /var/cache/mise
      BW_SERVER: https://vaultwarden.06222001.xyz
    commands:
      - mkdir -p /var/cache/apk
      - ln -s /var/cache/apk /etc/apk/cache
      - apk add openssh nodejs npm curl
      - npm install -g @bitwarden/cli@2026.6.0 --cache /var/cache/npm --prefer-offline
      - bw config server "$BW_SERVER"
      - bw login --apikey
      - export BW_SESSION=$(bw unlock --passwordenv BW_PASSWORD --raw)
      - curl https://mise.run | sh
      - export PATH="$HOME/.local/bin:$PATH"
      - mkdir -p /root/.ssh/
      - export SSH_KEY=$(mise exec fnox@1.28.0 -- fnox get SSH_KEY)
      - echo "$SSH_KEY" | tr -d '\r' > /root/.ssh/id_rsa
      - chmod 600 /root/.ssh/id_rsa
      - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > /root/.ssh/config
      - ssh "$SSH_HOST" "
        cd "$PROJECT_DIRECTORY";
        docker compose down;
        git restore . && git pull origin "$CI_COMMIT_BRANCH" --force --rebase;
        docker compose up -d;
        docker image prune -af;
        sleep 60;
        docker compose logs;"
    volumes:
      - /var/cache/apk:/var/cache/apk
      - /var/cache/npm:/var/cache/npm
      - /var/cache/mise:/var/cache/mise
  - name: discord
    image: appleboy/drone-discord
    settings:
      webhook_id:
        from_secret: DISCORD_WEBHOOK_ID
      webhook_token:
        from_secret: DISCORD_WEBHOOK_TOKEN
      message: >
        {{#success build.status}}
          ✅ [{{repo.name}}] Successful local deployment for build #{{build.number}}
          Branch: {{commit.branch}}
          Commit: {{commit.sha}}:{{commit.message}}
          By: {{commit.author}}
        {{else}}
          ❌ [{{repo.name}}] Failed local deployment for build #{{build.number}}
          Branch: {{commit.branch}}
          Commit: {{commit.sha}}:{{commit.message}}
          By: {{commit.author}}
        {{/success}}
    when:
      status: [ success, failure ]

when:
  - branch: master
    event:
      - push
      - manual

depends_on:
  - test