# Deployment step for Woodpecker CI/CD
# Git-backed, images pulled from remote registry

steps:
  - name: deploy
    image: alpine:latest
    environment:
      SSH_HOST:
        from_secret: SSH_HOST_2
      PROJECT_DIRECTORY:
        from_secret: PROJECT_DIRECTORY_2
      SSH_KEY:
        from_secret: SSH_KEY
    commands:
      - apk add openssh
      - mkdir -p /root/.ssh/
      - echo "$SSH_KEY" | tr -d '\r' > /root/.ssh/id_rsa
      - chmod 600 /root/.ssh/id_rsa
      - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > /root/.ssh/config
      - ssh "$SSH_HOST" "
          cd $PROJECT_DIRECTORY;
          docker compose down;
          git restore . && git pull origin $CI_COMMIT_BRANCH --force --rebase;
          rm -fv config/remote.yaml;
          for f in config/*.yaml; do sed -i.bak -E 's/^([[:space:]]*group:[[:space:]]*)(.*)$/\\1Remote - \\2/' \"\$f\" && rm -f \"\$f.bak\"; done;
          docker compose up -d;
          docker image prune -af;
          sleep 60;
          docker compose logs;
        "
  - name: discord
    image: appleboy/drone-discord
    settings:
      webhook_id:
        from_secret: DISCORD_WEBHOOK_ID
      webhook_token:
        from_secret: DISCORD_WEBHOOK_TOKEN
      message: >
        {{#success build.status}}
          ✅ [{{repo.name}}] Successful remote deployment for build #{{build.number}}
          Branch: {{commit.branch}}
          Commit: {{commit.sha}}:{{commit.message}}
          By: {{commit.author}}
        {{else}}
          ❌ [{{repo.name}}] Failed remote deployment for build #{{build.number}}
          Branch: {{commit.branch}}
          Commit: {{commit.sha}}:{{commit.message}}
          By: {{commit.author}}
        {{/success}}
    when:
      status: [ success, failure ]

when:
  - branch: master
    event:
      - push
      - manual

depends_on:
  - test

skip_clone: true